In [1]:
from pathlib import Path
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_colwidth", None)

In [3]:
DATA_DIR = Path("../data/raw")
files = sorted(DATA_DIR.glob("*"))

print(f"Total files: {len(files)}")

for file in files:
    print(file.name)

Total files: 2
.gitkeep
inspire

In [4]:
tables = {}

for file in DATA_DIR.glob("*.csv"):
    print(f"Loading {file.name}")

    tables[file.stem] = pd.read_csv(
        file,
        low_memory=False
    )

In [5]:
tables.keys()

dict_keys([])

In [7]:
from pathlib import Path

for file in Path("../data/raw").rglob("*"):
    print(file)

..\data\raw\.gitkeep
..\data\raw\inspire
..\data\raw\inspire\CHANGELOG.txt
..\data\raw\inspire\department.csv
..\data\raw\inspire\diagnosis.csv.gz
..\data\raw\inspire\icd10_excluded.csv
..\data\raw\inspire\labs.csv.gz
..\data\raw\inspire\LICENSE.txt
..\data\raw\inspire\medications.csv.gz
..\data\raw\inspire\operations.csv.gz
..\data\raw\inspire\parameters.csv
..\data\raw\inspire\schema.csv
..\data\raw\inspire\SHA256SUMS.txt
..\data\raw\inspire\vitals.csv.gz
..\data\raw\inspire\ward_vitals.csv.gz

In [9]:
DATA_DIR = Path("../data/raw/inspire")
files = sorted(DATA_DIR.glob("*"))

for file in files:
    print(file.name)

CHANGELOG.txt
department.csv
diagnosis.csv.gz
icd10_excluded.csv
labs.csv.gz
LICENSE.txt
medications.csv.gz
operations.csv.gz
parameters.csv
schema.csv
SHA256SUMS.txt
vitals.csv.gz
ward_vitals.csv.gz

In [11]:
tables = {}

for file in DATA_DIR.glob("*"):
    if file.suffix not in [".csv", ".gz"]:
        continue

    print(f"Loading {file.name}")

    tables[file.stem] = pd.read_csv(
        file,
        compression="infer",
        low_memory=False,
    );    print(f"Loading {file.name}")

    tables[file.stem] = pd.read_csv(
        file,
        low_memory=False
    )

Loading department.csv
Loading department.csv
Loading diagnosis.csv.gz
Loading diagnosis.csv.gz
Loading icd10_excluded.csv
Loading icd10_excluded.csv
Loading labs.csv.gz
Loading labs.csv.gz
Loading medications.csv.gz
Loading medications.csv.gz
Loading operations.csv.gz
Loading operations.csv.gz
Loading parameters.csv
Loading parameters.csv
Loading schema.csv
Loading schema.csv
Loading vitals.csv.gz
Loading vitals.csv.gz
Loading ward_vitals.csv.gz
Loading ward_vitals.csv.gz

In [12]:
tables.keys()

dict_keys(['department', 'diagnosis.csv', 'icd10_excluded', 'labs.csv', 'medications.csv', 'operations.csv', 'parameters', 'schema', 'vitals.csv', 'ward_vitals.csv'])

In [13]:
summary = []

for name, df in tables.items():
    summary.append({
        "Table": name,
        "Rows": len(df),
        "Columns": len(df.columns)
    })

summary = (
    pd.DataFrame(summary)
      .sort_values("Rows", ascending=False)
)

summary

             Table      Rows  Columns
8       vitals.csv  66029310        5
9  ward_vitals.csv  45239260        4
3         labs.csv  19464283        4
4  medications.csv  10854338        5
1    diagnosis.csv   2464620        3
5   operations.csv    130960       29
6       parameters       129        4
7           schema        54        4
2   icd10_excluded        31        2
0       department        16        2

In [14]:
for name, df in tables.items():
    print("=" * 80)
    print(name.upper())
    print("=" * 80)

    display(df.head())

    print("\nColumns:")
    print(df.columns.tolist())

    print("\n")

================================================================================
DEPARTMENT
================================================================================

  Abbreviations                Full name
0            AN           Anesthesiology
1           CTS  Cardio-Thoracic Surgery
2            DM              Dermatology
3            EM       Emergency Medicine
4            GS          General Surgery

Columns:
['Abbreviations', 'Full name']


================================================================================
DIAGNOSIS.CSV
================================================================================

   subject_id  chart_time icd10_cm
0   190852492      325440      R06
1   190852492      325440      G20
2   142367193           0      I61
3   178346414       80640      A16
4   178346414       80640      J98

Columns:
['subject_id', 'chart_time', 'icd10_cm']


================================================================================
ICD10_EXCLUDED
================================================================================

                 ICD-10-CM                                 Causes
0                     A30                                 Leprosy
1                     A31            Other mycobacteria infection
2  A5,A60,A61,A62,A63,A64   Sexual transmitted diseases (A50~A64)
3                     A81                           Prion disease
4     B20,B21,B22,B23,B24                 HIV infection (B20~B24)

Columns:
['ICD-10-CM', 'Causes']


================================================================================
LABS.CSV
================================================================================

   subject_id  chart_time      item_name  value
0   133338290       86155  total_protein    6.9
1   133338290       86155         sodium  140.0
2   133338290       86155      potassium    4.4
3   133338290       86155       platelet  152.0
4   133338290       93150        glucose  120.0

Columns:
['subject_id', 'chart_time', 'item_name', 'value']


================================================================================
MEDICATIONS.CSV
================================================================================

   subject_id  chart_time route      drug_name atc_code
0   117512122     2832985    po     pregabalin  N03AX16
1   117512122     2833610    po     pregabalin  N03AX16
2   117512122     2832985    po  levetiracetam  N03AX14
3   117512122     2833610    po  levetiracetam  N03AX14
4   117512122     2832985    po     famotidine  A02BA03

Columns:
['subject_id', 'chart_time', 'route', 'drug_name', 'atc_code']


================================================================================
OPERATIONS.CSV
================================================================================

,op_id,subject_id,hadm_id,case_id,opdate,age,sex,weight,height,race,asa,emop,department,antype,icd10_pcs,orin_time,orout_time,opstart_time,opend_time,admission_time,discharge_time,anstart_time,anend_time,cpbon_time,cpboff_time,icuin_time,icuout_time,inhosp_death_time,allcause_death_time
0,484069807,178742874,229842382,NaN,0,30,F,50.0,155.0,Asian,NaN,1,OT,General,09B70,1110,1245,1140.0,1230.0,0,7195,1120.0,1235.0,NaN,NaN,NaN,NaN,NaN,NaN
1,446270725,158995752,257857903,NaN,0,70,M,45.0,170.0,Asian,NaN,1,GS,General,0WJG0,1340,1550,1370.0,1540.0,0,70555,1345.0,1540.0,NaN,NaN,1550.0,19595.0,69860.0,106560.0
2,406892271,108553242,200664328,NaN,61920,50,F,70.0,165.0,Asian,NaN,1,OG,General,0DHS0,62165,62395,62200.0,62380.0,0,178555,62170.0,62370.0,NaN,NaN,NaN,NaN,NaN,718560.0
3,478413008,133278262,277235295,NaN,0,35,F,55.0,NaN,Asian,NaN,1,OG,Neuraxial,10D00,210,340,230.0,330.0,0,5755,215.0,340.0,NaN,NaN,NaN,NaN,NaN,NaN
4,468516791,116924034,299190423,NaN,17280,45,F,45.0,150.0,Asian,1.0,0,OG,General,0JQC0,17945,18080,17970.0,18070.0,0,25915,17950.0,18070.0,NaN,NaN,NaN,NaN,NaN,NaN

Columns:
['op_id', 'subject_id', 'hadm_id', 'case_id', 'opdate', 'age', 'sex', 'weight', 'height', 'race', 'asa', 'emop', 'department', 'antype', 'icd10_pcs', 'orin_time', 'orout_time', 'opstart_time', 'opend_time', 'admission_time', 'discharge_time', 'anstart_time', 'anend_time', 'cpbon_time', 'cpboff_time', 'icuin_time', 'icuout_time', 'inhosp_death_time', 'allcause_death_time']


================================================================================
PARAMETERS
================================================================================

  Table    Label  Unit                            Description
0  labs  albumin  g/dL                                Albumin
1  labs      alp  IU/L                   Alkaline phosphatase
2  labs      alt  IU/L                   Alanine transaminase
3  labs     aptt   sec  Activated partial thromboplastin time
4  labs      ast  IU/L                 Aspartate transaminase

Columns:
['Table', 'Label', 'Unit', 'Description']


================================================================================
SCHEMA
================================================================================

,Table,Variable,Type,Description
0,operations,op_id,Number,A random number starts with 4 for the operation.
1,NaN,subject_id,Number,A random number starts with 1 for the patient.
2,NaN,hadm_id,Number,A random number starts with 2 for hospital admission.
3,NaN,case_id,Number,A linker to VitalDB Open Dataset
4,NaN,opdate,Relative Time,Operation date

Columns:
['Table', 'Variable', 'Type', 'Description']


================================================================================
VITALS.CSV
================================================================================

       op_id  subject_id  chart_time item_name  value
0  435959808   181409183        1985    minvol    4.4
1  435959808   181409183        1985        vt  512.0
2  435959808   181409183        1985        rr    9.0
3  435959808   181409183        1985       pip   23.0
4  435959808   181409183        2005    minvol    4.4

Columns:
['op_id', 'subject_id', 'chart_time', 'item_name', 'value']


================================================================================
WARD_VITALS.CSV
================================================================================

   subject_id  chart_time item_name  value
0   104192463         580      spo2   98.0
1   104192463         580  nibp_sbp  169.0
2   104192463         580        hr   96.0
3   104192463         580  nibp_dbp  100.0
4   104192463         580        bt   36.5

Columns:
['subject_id', 'chart_time', 'item_name', 'value']

In [15]:
column_summary = []

for name, df in tables.items():

    for column in df.columns:

        column_summary.append({
            "Table": name,
            "Column": column,
            "Datatype": str(df[column].dtype),
            "Missing (%)":
                round(df[column].isna().mean() * 100, 2)
        })

column_summary = pd.DataFrame(column_summary)

column_summary.head()

           Table         Column Datatype  Missing (%)
0     department  Abbreviations   object          0.0
1     department      Full name   object          0.0
2  diagnosis.csv     subject_id    int64          0.0
3  diagnosis.csv     chart_time    int64          0.0
4  diagnosis.csv       icd10_cm   object          0.0

In [16]:
column_summary.to_csv(
    "../docs/inspire_columns.csv",
    index=False
)

In [17]:
tables = {
    name.replace(".csv", ""): dataframe
    for name, dataframe in tables.items()
}

tables.keys()

dict_keys(['department', 'diagnosis', 'icd10_excluded', 'labs', 'medications', 'operations', 'parameters', 'schema', 'vitals', 'ward_vitals'])

In [18]:
tables["parameters"].head(30)

,Table,Label,Unit,Description
0,labs,albumin,g/dL,Albumin
1,labs,alp,IU/L,Alkaline phosphatase
2,labs,alt,IU/L,Alanine transaminase
3,labs,aptt,sec,Activated partial thromboplastin time
4,labs,ast,IU/L,Aspartate transaminase
5,labs,be,mmol/L,Base excess in arterial blood gas analysis
6,labs,bun,mg/dL,Blood urea nitrogen
7,labs,calcium,mg/dL,Calcium
8,labs,chloride,mmol/L,Chloride
9,labs,ck,IU/L,Creatine kinase
10,labs,ckmb,ug/L,Creatine kinase-MB
11,labs,creatinine,mg/dL,Creatinine
12,labs,crp,mg/dL,High-sensitive CRP
13,labs,d_dimer,mg/L,"D-dimer (fibrinogen equivalent units, FEU)"
14,labs,fibrinogen,mg/dL,Fibrinogen
15,labs,glucose,mg/dL,Glucose
16,labs,hb,g/dL,Hemoglobin
17,labs,hba1c,%,Hemoglobin A1c
18,labs,hco3,mmol/L,HCO3 in arterial blood gas analysis
19,labs,hct,%,Hematocrit
20,labs,ica,mmol/L,Ionized calcium
21,labs,lacate,mmol/L,Lactate
22,labs,lymphocyte,%,Lymphocyte percentage
23,labs,paco2,mmHg,Partial pressure of carbon dioxide in arterial blood gas analysis
24,labs,pao2,mmHg,Partial pressure of oxygen in arterial blood gas analysis
25,labs,ph,NaN,pH in arterial blood gas analysis
26,labs,phosphorus,mg/dL,Phosphorus
27,labs,platelet,/nL,Platelet count
28,labs,potassium,mmol/L,Potassium
29,labs,ptinr,INR,Prothrombin time

In [19]:
tables["parameters"][
    tables["parameters"]["Table"]
    .astype(str)
    .str.contains("vital", case=False, na=False)
]

,Table,Label,Unit,Description
38,vitals,aft,ug,Infused dose of alfentanil
39,vitals,air,L/min,Flow of medical air
40,vitals,alb20,mL,Infused volume of albumin 20%
41,vitals,alb5,mL,Infused volume of albumin 5%
42,vitals,art_dbp,mmHg,Arterial diastolic blood pressure
43,vitals,art_mbp,mmHg,Arterial mean blood pressure
44,vitals,art_sbp,mmHg,Arterial systolic blood pressure
45,vitals,bis,NaN,Bispectral index
46,vitals,bt,Celsius,Body temperature
47,vitals,cbro2,%,cerebral regional oxygen saturation
48,vitals,ci,L/min/m2,Cardiac Index
49,vitals,cpat,mL/cmH2O,Patient compliance (VT / (Pplat - PEEP))
50,vitals,cryo,Unit,Transfused cryoprecipitate
51,vitals,cvp,mmHg,Central venous pressure
52,vitals,d10w,mL,Infused volume of Dextrose 10% water
53,vitals,d50w,mL,Infused volume of Dextrose 50% water
54,vitals,d5w,mL,Infused volume of Dextrose 5% water
55,vitals,ds,mL,Infused volume of Dextrose Saline
56,vitals,dobui,ug/kg/min,Rate of dobutamine continuous infusion
57,vitals,dopai,ug/kg/min,Rate of dopamine continuous infusion
58,vitals,ebl,mL,Estimated blood loss
59,vitals,eph,mg,Injected dose of Ephedrine
60,vitals,epi,ug,Injected dose of Epinephrine
61,vitals,epii,ug/kg/min,Rate of epinephrine continuous infusion
62,vitals,etco2,mmHg,End tidal concentration of carbon dioxide
63,vitals,etdes,%,End tidal concentration of desflurane
64,vitals,etgas,%,End tidal concentration of anesthetic agent
65,vitals,etiso,%,End tidal concentration of isoflurane
66,vitals,etsevo,%,End tidal concentration of sevoflurane
67,vitals,ffp,Unit,Transfused fresh frozen plasma
68,vitals,fio2,%,Fraction of inspired oxygen
69,vitals,ftn,ug,Injected dose of fentanyl
70,vitals,hes,mL,Infused volume of Hydroxyethyl-starch solution
71,vitals,hns,mL,Infused volume of half normal saline
72,vitals,hr,/min,Heart rate
73,vitals,hs,mL,Infused volume of Hartmann's solution
74,vitals,mdz,mg,Injected dose of midazolam
75,vitals,minvol,L/min,Minute ventilation
76,vitals,mlni,ug/kg/min,Rate of milrinone continuous infusion
77,vitals,n2o,L/min,Flow of nitrous oxide
78,vitals,nepi,ug/kg/min,Rate of norepinephrine continuous infusion
79,vitals,nibp_dbp,mmHg,Non-invasive diastolic blood pressure
80,vitals,nibp_mbp,mmHg,Non-invasive mean blood pressure
81,vitals,nibp_sbp,mmHg,Non-invasive systolic blood pressure
82,vitals,ns,mL,Infused volume of normal saline
83,vitals,ntgi,ug/kg/min,Rate of nitroglycerin continuous infusion
84,vitals,o2,L/min,Flow of oxygen
85,vitals,pap_dbp,mmHg,Pulmonary artery diastolic blood pressure
86,vitals,pap_mbp,mmHg,Pulmonary artery mean blood pressure
87,vitals,pap_sbp,mmHg,Pulmonary artery systolic blood pressure
88,vitals,pc,Unit,Transfused platelet concentrate
89,vitals,peep,cmH2O,Positive end expiratory pressure
90,vitals,pepi,ug/h,Rate of phenylephrine continuous infusion
91,vitals,phe,ug,Injected dose of phenyephrine
92,vitals,pheresis,Unit,Transfused platelet pheresis
93,vitals,pip,cmH2O,Peak inspiratory pressure
94,vitals,pmean,cmH2O,Mean airway pressure
95,vitals,ppf,mg,Injected dose of propofol
96,vitals,ppfi,ug/mL,Target concentration of propofol
97,vitals,pplat,cmH2O,Plateau pressure
98,vitals,psa,mL,Infused volume of plasma solution
99,vitals,rbc,Unit,Transfused red blood cell
100,vitals,rfti,ng/mL,Target concentration of remifentanil
101,vitals,rr,/min,Respiration rate
102,vitals,sft,ug,Injected dose of sufentanil
103,vitals,spo2,%,Peripheral oxygen saturation
104,vitals,sti,mV,ST segment elevation in lead I
105,vitals,stii,mV,ST segment elevation in lead II
106,vitals,stiii,mV,ST segment elevation in lead III
107,vitals,stv5,mV,ST segment elevation in lead V5
108,vitals,svi,mL/m2,Stroke volume index
109,vitals,uo,mL,Urine output
110,vitals,vaso,Unit,Injected dose of vasopressin
111,vitals,vt,mL,Tidal volume
112,ward_vitals,art_sbp,mmHg,Arterial systolic blood pressure
113,ward_vitals,bt,Celsius,Body Temperature
114,ward_vitals,crrt,0/1,Use of hemodialysis or continuous renal replacement therapy
115,ward_vitals,ecmo,0/1,Use of extracorporeal membrane oxygenator
116,ward_vitals,fio2,%,Fraction inspired oxygen
117,ward_vitals,gcs_e,1/2/3/4,Glasgow Coma Scale (Eye)
118,ward_vitals,gcs_m,1/2/3/4/5/6,Glasgow Coma Scale (Motor)
119,ward_vitals,gcs_v,1/2/3/4/5,Glasgow Coma Scale (Verbal)
120,ward_vitals,hr,/min,Heart rate
121,ward_vitals,iabp,0/1,Existence of any parameter related to use of Intra-aortic baloon pump
122,ward_vitals,nibp_dbp,mmHg,Non-invasive diastolic blood pressure
123,ward_vitals,nibp_mbp,mmHg,Non-invasive mean blood pressure
124,ward_vitals,nibp_sbp,mmHg,Non-invasive systolic blood pressure
125,ward_vitals,rr,/min,Respiration rate
126,ward_vitals,spo2,%,Peripheral oxygen saturation
127,ward_vitals,uo,mL,Urine output
128,ward_vitals,vent,0/1,Use of mechanical ventilation

In [20]:
tables["parameters"][
    tables["parameters"]["Table"]
    .astype(str)
    .str.contains("lab", case=False, na=False)
]

,Table,Label,Unit,Description
0,labs,albumin,g/dL,Albumin
1,labs,alp,IU/L,Alkaline phosphatase
2,labs,alt,IU/L,Alanine transaminase
3,labs,aptt,sec,Activated partial thromboplastin time
4,labs,ast,IU/L,Aspartate transaminase
5,labs,be,mmol/L,Base excess in arterial blood gas analysis
6,labs,bun,mg/dL,Blood urea nitrogen
7,labs,calcium,mg/dL,Calcium
8,labs,chloride,mmol/L,Chloride
9,labs,ck,IU/L,Creatine kinase
10,labs,ckmb,ug/L,Creatine kinase-MB
11,labs,creatinine,mg/dL,Creatinine
12,labs,crp,mg/dL,High-sensitive CRP
13,labs,d_dimer,mg/L,"D-dimer (fibrinogen equivalent units, FEU)"
14,labs,fibrinogen,mg/dL,Fibrinogen
15,labs,glucose,mg/dL,Glucose
16,labs,hb,g/dL,Hemoglobin
17,labs,hba1c,%,Hemoglobin A1c
18,labs,hco3,mmol/L,HCO3 in arterial blood gas analysis
19,labs,hct,%,Hematocrit
20,labs,ica,mmol/L,Ionized calcium
21,labs,lacate,mmol/L,Lactate
22,labs,lymphocyte,%,Lymphocyte percentage
23,labs,paco2,mmHg,Partial pressure of carbon dioxide in arterial blood gas analysis
24,labs,pao2,mmHg,Partial pressure of oxygen in arterial blood gas analysis
25,labs,ph,NaN,pH in arterial blood gas analysis
26,labs,phosphorus,mg/dL,Phosphorus
27,labs,platelet,/nL,Platelet count
28,labs,potassium,mmol/L,Potassium
29,labs,ptinr,INR,Prothrombin time
30,labs,sao2,%,Oxygen saturation in arterial blood gas analysis
31,labs,seg,%,Segmented neutrophil percentage
32,labs,sodium,mmol/L,Sodium
33,labs,total_bilirubin,mg/dL,Total bilirubin
34,labs,total_protein,g/dL,Total protein
35,labs,troponin_i,ug/L,Troponin-I
36,labs,troponin_t,ug/L,Troponin-T
37,labs,wbc,/nL,White blood cell count

In [21]:
vital_items = (
    tables["vitals"]["item_name"]
    .value_counts()
    .rename_axis("item_name")
    .reset_index(name="records")
)

vital_items

   item_name  records
0         rr  5446900
1         hr  4708667
2       spo2  4221511
3      etco2  3777647
4       fio2  3608544
5        pip  3433326
6         bt  3307926
7         vt  3290356
8     minvol  3238501
9      pmean  2883974
10      peep  2566848
11   art_mbp  2355456
12   art_sbp  2249106
13   art_dbp  2242742
14      stii  2129745
15  nibp_mbp  2053793
16  nibp_dbp  2050617
17  nibp_sbp  2050547
18     pplat  1750049
19      cpat  1683283
20     etgas  1455481
21       cvp   915414
22       bis   653906
23     stiii   341673
24       sti   332545
25      stv5   325737
26        o2   315655
27       air   262562
28        hs   238102
29       psa   217737
30       ebl   198984
31   pap_mbp   165994
32        uo   157712
33   pap_sbp   149592
34   pap_dbp   148308
35    etsevo   140141
36      rfti   105718
37        ci   104463
38        ns    99608
39       eph    95181
40       hes    90231
41     etdes    86092
42      ppfi    69243
43       phe    59585
44       ppf    50857
45       rbc    44214
46       ftn    38200
47       svi    28494
48      nepi    19426
49       ffp    11270
50     dobui     8018
51      ntgi     7579
52       mdz     7436
53       n2o     6466
54     alb20     5826
55        pc     4991
56     dopai     3712
57       epi     1952
58      epii     1878
59       sft     1796
60       hns     1762
61      cryo     1748
62     cbro2     1290
63      vaso     1205
64      mlni     1037
65      alb5      430
66      d50w      208
67  pheresis      135
68       d5w      128
69      d10w       29
70       aft        9
71        ds        7
72     etiso        5

In [22]:
ward_vital_items = (
    tables["ward_vitals"]["item_name"]
    .value_counts()
    .rename_axis("item_name")
    .reset_index(name="records")
)

ward_vital_items

   item_name  records
0         hr  9870814
1   nibp_sbp  6778087
2   nibp_dbp  6777533
3         rr  6112706
4         bt  5045574
5       spo2  4473175
6   nibp_mbp  1957817
7       fio2  1153774
8         uo  1097580
9       vent   504794
10     gcs_e   503516
11     gcs_m   503347
12     gcs_v   198650
13      crrt   187377
14      ecmo    67921
15      iabp     6595

In [23]:
ward_vital_items = (
    tables["ward_vitals"]["item_name"]
    .value_counts()
    .rename_axis("item_name")
    .reset_index(name="records")
)

ward_vital_items

   item_name  records
0         hr  9870814
1   nibp_sbp  6778087
2   nibp_dbp  6777533
3         rr  6112706
4         bt  5045574
5       spo2  4473175
6   nibp_mbp  1957817
7       fio2  1153774
8         uo  1097580
9       vent   504794
10     gcs_e   503516
11     gcs_m   503347
12     gcs_v   198650
13      crrt   187377
14      ecmo    67921
15      iabp     6595

In [24]:
lab_items = (
    tables["labs"]["item_name"]
    .value_counts()
    .rename_axis("item_name")
    .reset_index(name="records")
)

lab_items.head(100)

          item_name  records
0           glucose  1375911
1        creatinine  1001373
2               hct   976162
3         potassium   942971
4            sodium   939461
5                hb   811208
6               wbc   755973
7          platelet   744486
8          chloride   719216
9        lymphocyte   703989
10              seg   691085
11              bun   677271
12          calcium   672812
13       phosphorus   665814
14          albumin   646157
15  total_bilirubin   622237
16              alt   618219
17              ast   618125
18    total_protein   610151
19              alp   605213
20              crp   435815
21             sao2   381279
22             hco3   380897
23            ptinr   360337
24               ph   326572
25             pao2   325703
26            paco2   325499
27             aptt   316969
28              ica   281731
29       fibrinogen   261458
30               be   237386
31           lacate   220198
32             ckmb    61705
33               ck    60746
34       troponin_i    48958
35            hba1c    40434
36       troponin_t      445
37          d_dimer      317

In [25]:
lab_items.to_csv(
    "../docs/lab_items.csv",
    index=False
)

In [26]:
search_terms = [
    "hemoglobin",
    "white",
    "platelet",
    "creatinine",
    "urea",
    "bun",
    "sodium",
    "potassium",
    "glucose",
    "albumin",
    "bilirubin",
    "inr",
    "prothrombin",
    "lactate",
]

pattern = "|".join(search_terms)

lab_items[
    lab_items["item_name"]
    .str.contains(pattern, case=False, na=False)
]

          item_name  records
0           glucose  1375911
1        creatinine  1001373
3         potassium   942971
4            sodium   939461
7          platelet   744486
11              bun   677271
14          albumin   646157
15  total_bilirubin   622237
23            ptinr   360337

In [29]:
tables["diagnosis"]["icd10_cm"].nunique()

1136

In [30]:
tables["diagnosis"]["icd10_cm"].value_counts().head(50)

icd10_cm
C50    155865
N18     99671
H26     69965
C16     53963
C18     49349
E14     43365
C34     39431
R52     38539
I10     34654
C20     34524
C22     33926
H40     33719
Z94     31745
E04     30509
C73     28881
C67     23613
N40     23277
M48     22299
C61     22018
D25     21556
N83     20888
I20     20453
N64     19934
K29     19285
E11     18967
D05     16566
J34     16283
H66     16220
K80     16040
C25     15979
K21     15867
M17     14219
J32     14166
H36     13950
Z34     13873
C79     13611
H04     13469
D35     13299
I48     12915
R91     12910
C56     12766
C64     12502
R94     12252
C78     12208
N80     12186
C49     12154
H33     12017
C71     11527
B18     11417
I63     11275
Name: count, dtype: int64

In [31]:
diagnoses_per_patient = (
    tables["diagnosis"]
    .groupby("subject_id")
    .size()
)

diagnoses_per_patient.describe()

count    95360.000000
mean        25.845428
std         41.924003
min          1.000000
25%          8.000000
50%         15.000000
75%         28.000000
max       2225.000000
dtype: float64

In [32]:
tables["medications"]["route"].value_counts().head(30)

route
po    6449851
iv    3535134
ex     869353
Name: count, dtype: int64

In [33]:
tables["medications"]["drug_name"].value_counts().head(50)

drug_name
ambroxol                            771723
acetaminophen                       404094
famotidine                          396050
tramadol                            378106
magnesium oxide                     314696
cefazolin                           237498
acetylcysteine                      204606
mosapride                           157099
udca                                152842
piperacillin                        151922
tazobactam                          151458
flomoxef                            128157
erdosteine                          127093
ipratropium                         112677
pantoprazole                        107004
potassium chloride                  102493
levetiracetam                       100989
oxycodone                           100027
ibuprofen                            97115
itopride                             96387
sucralfate                           93625
vancomycin                           92891
lactulose                            92874
metronidazole                        90147
furosemide                           89677
salbutamol                           88651
amlodipine                           86537
metoclopramide                       83372
arginine                             82844
moxifloxacin                         81857
ramosetron                           80478
cefotetan                            75002
acetyl cysteine                      74605
rebamipide                           70953
ranitidine                           65828
amylase                              65541
protease                             65541
lipase                               65541
bisacodyl                            65219
dexamethasone disodium phosphate     63399
zaltoprofen                          59895
prednisolon                          58876
diltiazem                            54668
ketorolac                            54349
aspirin enteric coated               53868
tacrolimus                           53241
metformin                            49636
ceftriaxone                          49216
spironolactone                       47962
hyaluronate                          47202
Name: count, dtype: int64

In [34]:
tables["medications"]["atc_code"].value_counts().head(50)

atc_code
R05CB06    771723
N02BE01    413170
A02BA03    396050
N02AX02    378106
A02AA02    314696
R05CB01    279211
J01DB04    237498
A03FA09    157099
A05AA02    152842
J01CA12    151922
J01CG02    151458
A06AB02    128618
J01DC14    128157
R05CB15    127093
A12BA01    126276
R03BB01    112677
A02BC02    107004
N03AX14    100989
N02AA05    100027
M01AE01     97115
A03FA07     96387
A02BX02     93985
A07AA09     92891
A06AD11     92874
J01XD01     90147
C03CA01     89677
C08CA01     89478
R03CC02     88651
A03FA01     83372
B05XB01     82844
J01MA14     81857
A04AA       80478
B01AC06     79314
J01DC05     75002
A02BX14     70953
H02AB06     70005
A02BA02     65828
A09AA02     65541
A02BC03     65381
M01AE       59895
C08DB01     54668
M01AB15     54349
L04AD02     53241
A07FA01     51820
A10BA02     50612
J01DD04     49216
S01KA01     48270
C03DA01     47962
G04CA02     45772
J01DH02     45673
Name: count, dtype: int64

In [35]:
tables["schema"][
    tables["schema"]["Variable"].isin([
        "chart_time",
        "opdate",
        "orin_time",
        "opstart_time",
        "admission_time",
    ])
]

,Table,Variable,Type,Description
4,NaN,opdate,Relative Time,Operation date
15,NaN,orin_time,Relative Time,The time for entering the operating room
17,NaN,opstart_time,Relative Time,The time for starting the operation
19,NaN,admission_time,Relative Time,The time for hospital admission
30,NaN,chart_time,Relative Time,The time for the diagnosis recorded
34,NaN,chart_time,Relative Time,The time for the measurement recorded
38,NaN,chart_time,Relative Time,The time for the measurement recorded
42,NaN,chart_time,Relative Time,The time for the measurement recorded
46,NaN,chart_time,Relative Time,The time for the measurement recorded

In [36]:
tables["schema"].to_string(index=False)

'      Table            Variable          Type                                                          Description\n operations               op_id        Number                     A random number starts with 4 for the operation.\n        NaN          subject_id        Number                       A random number starts with 1 for the patient.\n        NaN             hadm_id        Number                A random number starts with 2 for hospital admission.\n        NaN             case_id        Number                                     A linker to VitalDB Open Dataset\n        NaN              opdate Relative Time                                                       Operation date\n        NaN                 age        Number                             Age of the patient on the operation date\n        NaN                 sex           M/F                                                   Sex of the patient\n        NaN              weight        Number                                     Weight measured before operation\n        NaN              height        Number                                        Age measured before operation\n        NaN                race        String                                                  Race of the patient\n        NaN                 asa     1/2/3/4/5 American Society of Anesthesiologists physical status classification\n        NaN                emop        Binary                                           Emergency of the operation\n        NaN          department        String                                    Surgical department for admission\n        NaN              antype        String               Anesthesia Type (General / Neuraxial / Regional / MAC)\n        NaN           icd10_pcs        String                                  ICD-10 Procedure Coding System code\n        NaN           orin_time Relative Time                             The time for entering the operating room\n        NaN          orout_time Relative Time                              The time for leaving the operating room\n        NaN        opstart_time Relative Time                                  The time for starting the operation\n        NaN          opend_time Relative Time                                 The time for finishing the operation\n        NaN      admission_time Relative Time                                      The time for hospital admission\n        NaN      discharge_time Relative Time                                      The time for hospital discharge\n        NaN        anstart_time Relative Time                                    The time for starting anaesthesia\n        NaN          anend_time Relative Time                                   The time for finishing anaesthesia\n        NaN          cpbon_time Relative Time                         The time for starting cardiopulmonary bypass\n        NaN         cpboff_time Relative Time                        The time for finishing cardiopulmonary bypass\n        NaN          icuin_time Relative Time                             The time for ICU admission after surgery\n        NaN         icuout_time Relative Time                             The time for ICU discharge after surgery\n        NaN   inhosp_death_time Relative Time                                       The time for in-hospital death\n        NaN allcause_death_time Relative Time                                         The time for all-cause death\n  diagnosis          subject_id        Number               The patient identifier defined in the operations table\n        NaN          chart_time Relative Time                                  The time for the diagnosis recorded\n        NaN            icd10_cm        String                                                ICD-10 Diagnosis Code\n     vitals               op_id        Number                 Operation identifier defined in the operations table\n        NaN          subject_id        Number               The patient identifier defined in the operations table\n        NaN          chart_time Relative Time                                The time for the measurement recorded\n        NaN           item_name        String                                            Label for the measurement\n        NaN               value        Number                                                       Measured value\nward_vitals          subject_id        Number               The patient identifier defined in the operations table\n        NaN          chart_time Relative Time                                The time for the measurement recorded\n        NaN           item_name        String                                            Label for the measurement\n        NaN               value        Number                                                       Measured value\n       labs          subject_id        Number               The patient identifier defined in the operations table\n        NaN          chart_time Relative Time                                The time for the measurement recorded\n        NaN           item_name        String                                            Label for the measurement\n        NaN               value        Number                                                       Measured value\nmedications          subject_id        Number               The patient identifier defined in the operations table\n        NaN          chart_time Relative Time                                The time for the measurement recorded\n        NaN           drug_name        String                                               Name of the medication\n        NaN          drug_name2        String                                              Name of the medication2\n        NaN          drug_name3        String                                              Name of the medication3\n        NaN               route        String                                  Route for the medication (po/iv/ex)\n        NaN            atc_code        String                                                         WHO ATC code\n        NaN           atc_code2        String                                                        WHO ATC code2\n        NaN           atc_code3        String                                                        WHO ATC code3'

In [37]:
vital_items
ward_vital_items
lab_items.head(100)

          item_name  records
0           glucose  1375911
1        creatinine  1001373
2               hct   976162
3         potassium   942971
4            sodium   939461
5                hb   811208
6               wbc   755973
7          platelet   744486
8          chloride   719216
9        lymphocyte   703989
10              seg   691085
11              bun   677271
12          calcium   672812
13       phosphorus   665814
14          albumin   646157
15  total_bilirubin   622237
16              alt   618219
17              ast   618125
18    total_protein   610151
19              alp   605213
20              crp   435815
21             sao2   381279
22             hco3   380897
23            ptinr   360337
24               ph   326572
25             pao2   325703
26            paco2   325499
27             aptt   316969
28              ica   281731
29       fibrinogen   261458
30               be   237386
31           lacate   220198
32             ckmb    61705
33               ck    60746
34       troponin_i    48958
35            hba1c    40434
36       troponin_t      445
37          d_dimer      317

In [38]:
vitals = tables["vitals"]

sorted(vitals["item_name"].unique())

['aft',
 'air',
 'alb20',
 'alb5',
 'art_dbp',
 'art_mbp',
 'art_sbp',
 'bis',
 'bt',
 'cbro2',
 'ci',
 'cpat',
 'cryo',
 'cvp',
 'd10w',
 'd50w',
 'd5w',
 'dobui',
 'dopai',
 'ds',
 'ebl',
 'eph',
 'epi',
 'epii',
 'etco2',
 'etdes',
 'etgas',
 'etiso',
 'etsevo',
 'ffp',
 'fio2',
 'ftn',
 'hes',
 'hns',
 'hr',
 'hs',
 'mdz',
 'minvol',
 'mlni',
 'n2o',
 'nepi',
 'nibp_dbp',
 'nibp_mbp',
 'nibp_sbp',
 'ns',
 'ntgi',
 'o2',
 'pap_dbp',
 'pap_mbp',
 'pap_sbp',
 'pc',
 'peep',
 'phe',
 'pheresis',
 'pip',
 'pmean',
 'ppf',
 'ppfi',
 'pplat',
 'psa',
 'rbc',
 'rfti',
 'rr',
 'sft',
 'spo2',
 'sti',
 'stii',
 'stiii',
 'stv5',
 'svi',
 'uo',
 'vaso',
 'vt']

In [39]:
labs = tables["labs"]

sorted(labs["item_name"].unique())

['albumin',
 'alp',
 'alt',
 'aptt',
 'ast',
 'be',
 'bun',
 'calcium',
 'chloride',
 'ck',
 'ckmb',
 'creatinine',
 'crp',
 'd_dimer',
 'fibrinogen',
 'glucose',
 'hb',
 'hba1c',
 'hco3',
 'hct',
 'ica',
 'lacate',
 'lymphocyte',
 'paco2',
 'pao2',
 'ph',
 'phosphorus',
 'platelet',
 'potassium',
 'ptinr',
 'sao2',
 'seg',
 'sodium',
 'total_bilirubin',
 'total_protein',
 'troponin_i',
 'troponin_t',
 'wbc']

In [40]:
def feature_coverage(df, feature_column):
    return (
        df[df["item_name"] == feature_column]
        .groupby("op_id")
        .size()
        .shape[0]
    )

In [41]:
total_operations = tables["operations"]["op_id"].nunique()

total_operations

130960

In [43]:
vital_features = [
    "hr",
    "nibp_sbp",
    "nibp_dbp",
    "rr",
    "spo2",
    "bt"
]

for feature in vital_features:
    coverage = feature_coverage(
        tables["vitals"],
        feature
    )

    print(
        f"{feature:12} {coverage:7} ({coverage/total_operations:.1%})"
    )

hr            130890 (99.9%)
nibp_sbp      129470 (98.9%)
nibp_dbp      129467 (98.9%)
rr            115925 (88.5%)
spo2          130912 (100.0%)
bt            100290 (76.6%)

In [44]:
lab_features = [
    "hb",
    "wbc",
    "platelet",
    "creatinine",
    "glucose",
    "sodium",
    "potassium",
    "albumin",
    "ptinr"
]

for feature in lab_features:
    coverage = feature_coverage(
        tables["labs"],
        feature
    )

    print(
        f"{feature:12} {coverage:7} ({coverage/total_operations:.1%})"
    )

KeyError: 'op_id'

In [45]:
def feature_coverage(df, feature_column, id_column):
    return (
        df[df["item_name"] == feature_column]
        .groupby(id_column)
        .size()
        .shape[0]
    )

In [46]:
coverage = feature_coverage(
    tables["vitals"],
    feature,
    "op_id"
)

In [47]:
coverage = feature_coverage(
    tables["labs"],
    feature,
    "subject_id"
)

In [48]:
lab_features = [
    "hb",
    "wbc",
    "platelet",
    "creatinine",
    "glucose",
    "sodium",
    "potassium",
    "albumin",
    "ptinr"
]

for feature in lab_features:
    coverage = feature_coverage(
        tables["labs"],
        feature
    )

    print(
        f"{feature:12} {coverage:7} ({coverage/total_operations:.1%})"
    )

TypeError: feature_coverage() missing 1 required positional argument: 'id_column'

In [49]:
print(tables["labs"].columns.tolist())

['subject_id', 'chart_time', 'item_name', 'value']

In [50]:
def feature_coverage(df, feature_column, subject_id):
    return (
        df[df["item_name"] == feature_column]
        .groupby(subject_id)
        .size()
        .shape[0]
    )

In [51]:
coverage = feature_coverage(
    tables["labs"],
    feature,
    "subject_id"
)

In [54]:
lab_features = [
    "hb",
    "wbc",
    "platelet",
    "creatinine",
    "glucose",
    "sodium",
    "potassium",
    "albumin",
    "ptinr"
]

for feature in lab_features:
    coverage = feature_coverage(
        tables["labs"],
        feature, "subject_id"
    )

    print(
        f"{feature:12} {coverage:7} ({coverage/total_operations:.1%})"
    )

hb             94521 (72.2%)
wbc            94215 (71.9%)
platelet       94154 (71.9%)
creatinine     99186 (75.7%)
glucose        92543 (70.7%)
sodium         93952 (71.7%)
potassium      93955 (71.7%)
albumin        93786 (71.6%)
ptinr          92243 (70.4%)

In [55]:
tables["operations"][[
    "op_id",
    "subject_id",
    "opstart_time"
]].head()

       op_id  subject_id  opstart_time
0  484069807   178742874        1140.0
1  446270725   158995752        1370.0
2  406892271   108553242       62200.0
3  478413008   133278262         230.0
4  468516791   116924034       17970.0

In [56]:
tables["labs"].head()

   subject_id  chart_time      item_name  value
0   133338290       86155  total_protein    6.9
1   133338290       86155         sodium  140.0
2   133338290       86155      potassium    4.4
3   133338290       86155       platelet  152.0
4   133338290       93150        glucose  120.0